[game]
hostname = "üòÇ Skill Issue Station [RU][LRP]"
desc = "–≠—Ç–æ—Ç —Å–µ—Ä–≤–µ—Ä - –ø–æ–ø—ã—Ç–∫–∞ –ø–æ–∫–∞–∑–∞—Ç—å —Ä—É—Å—Å–∫–æ–º—É —Å–æ–æ–±—â–µ—Å—Ç–≤—É –∏–≥—Ä—ã, —á—Ç–æ –µ—Å—Ç—å –¥—Ä—É–≥–∞—è —Å—Ç–æ—Ä–æ–Ω–∞, –±–µ–∑ –¥—É—à–Ω—ã—Ö –ø—Ä–∞–≤–∏–ª –∏ –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ç–æ—Ä–æ–≤, –≥–¥–µ –º–æ–∂–Ω–æ –≤–µ—Å–µ–ª–∏—Ç—å—Å—è –∏ –Ω–∞—Å–ª–∞–∂–¥–∞—Ç—å—Å—è –∏–≥—Ä–æ–π. –≠—Ç–æ –¥–æ—Å—Ç–∏–≥–Ω—É—Ç–æ —Å –ø–æ–º–æ—â—å—é –ª–∏—à—å –ø–µ—Ä–µ–≤–æ–¥–∞ –æ—Ñ—Ñ–∏—Ü–∏–∞–ª—å–Ω–æ–π —Å–±–æ—Ä–∫–∏ –∏–≥—Ä—ã, —É –∫–æ—Ç–æ—Ä–æ–π –ø—Ä–∏—è—Ç–Ω—ã–π –±–∞–ª–∞–Ω—Å –∏ –ø—Ä–æ—Å—Ç—ã–µ –ø—Ä–∞–≤–∏–ª–∞."
maxplayers = 100
soft_max_players = 50
map_rotation = true
role_timers = true

[infolinks]
bug_report = "https://github.com/Shegare/SIS-14/issues/new/choose"
discord    = "https://discord.gg/ZU2wCTA7gt"
github     = "https://github.com/Shegare/SIS-14"
appeal     = "https://discord.com/channels/1439525550032031806/1441447000636788899"

[server]
rules_file = "SISRuleset"

[rules]
time = 60.0

[hub]
advertise = true
tags = "lang:ru,rp:low,rp:med,region:eu_e"

[vote]
restart_required_ratio = 0.7

[admin]
see_own_notes = true
new_player_threshold = 600
alert.min_players_sharing_connection = 2

[atmos]
space_wind = true
mmos_spacing_speed = 1
max_explosion_range = 10

[shuttle]
emergency_early_launch_allowed = true

[ic]
flavor_text = true

[viewport]
maximum_width = 26
